config/routes.rb
Rails.application.routes.draw do
  devise_for :brands, :controllers => { registrations: 'brands/registrations' }
  devise_for :influencers, :controllers => { registrations: 'registrations' }

  # resources :campaigns

  root "site#index"
  get '/brands/dashboard' => 'brands#dashboard'
  get '/brands/create' => 'brands#create'

  get '/influencers/dashboard' => 'influencers#dashboard'
  get '/influencers/request' => 'influencers#request'

  post 'api/campaigns/create' => 'campaigns_apis#create'

  get '/influencers/campaigns/:industry' => 'campaigns_apis#technology'

  get '/campaigns' => 'hello#hello'

  get '/campaigns/:current_campaign_id' => 'campaigns_apis#add_campaign_to_influencer'

  get '/brands/campaigns/in_progress' => 'brands#campaigns_in_progress'

  delete '/brands/campaigns/:current_campaign_id/delete' => 'campaigns_apis#destroy', as: :brands_campaigns_delete

  get '/brands/campaigns/completed/:current_campaign_id' => 'brands#tweets_complete', as: :brands_tweets_complete
  
  get '/brands/campaigns/completed' => 'brands#completed_campaigns'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :industries
  has_many :campaigns

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :industries
  has_and_belongs_to_many :influencers
  has_many :brands
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_and_belongs_to_many :brands
  belongs_to :influencers
  belongs_to :campaigns
end

app/models/influencer.rb
class Influencer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :industries
  has_and_belongs_to_many :campaigns 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    if resource.is_a?(Influencer)
      influencers_dashboard_path
    else
      brands_dashboard_path
   end
  end

  $client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "85eU1gTcEK57lztgCwtzVVpeQ"
  config.consumer_secret     = "yDxvZFXu6C3FhRbLmt7VePIdpknW8reqBIMLlTWiGkrQiPWz5s"
  config.access_token        = "75638195-cc8rJKyivp5JFoZvTPN3xJqPIxPa6xQ4TK2BjcmYN"
  config.access_token_secret = "myPYGhXbMxSJDShWuWp6LLylgGhcOicPVxKfLOL4hPnZO"
  end


end

app/controllers/brands/registrations_controller.rb
class Brands::RegistrationsController < Devise::RegistrationsController
 
 def after_sign_in_path_for(resource)
  brands_dashboard_path #dont add redirect to this
 end

 private

 def sign_up_params
   params.require(:brand).permit(:username, :email, :password, :target_industry, :target_hashtag, :target_age_group, :target_demographic, :target_location, :password_confirmation)
 end

 def account_update_params
   params.require(:brand).permit(:username, :email, :password, :password_confirmation, :current_password, :target_industry, :target_hashtag, :target_age_group, :target_demographic, :target_location)
 end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
before_action :authenticate_brand!  

  def dashboard
    @campaign = Campaign.new
    @brands_campaigns = current_brand.campaigns.all.order(created_at: :desc)

  end

  def campaigns_in_progress
    @your_campaigns = current_brand.campaigns.where(completed: nil).order(created_at: :desc)
  end

  # def create
    
  # end

  def completed_campaigns
    @campaigns = current_brand.campaigns

    @campaigns.each do |campaign|
      campaign.influencers.each do |influencer|
         $client.search("from:#{influencer.username} #{campaign.hashtag}").collect do |tweet|
            campaign.completed = true if tweet.is_a?(Twitter::Tweet)
            campaign.save
         end
        end
      end

      @completed = current_brand.campaigns.where(completed: true).order(created_at: :desc)

     
    end




  def tweets_complete
    @current_campaign = Campaign.find_by_id(params[:current_campaign_id])
    @campaign_influencers = @current_campaign.influencers

    @tweets = []
    @campaign_influencers.each do |influencer|
    $client.search("from:#{influencer.username} ##{@current_campaign.hashtag}").take(100).collect do |tweet|
      @tweets.push("Username: " + tweet.user.screen_name + " " + "Hashtag: " + tweet.text)
    end
   end
  end
end

app/controllers/campaigns_apis_controller.rb
class CampaignsApisController < ApplicationController
  def create

    campaign = current_brand.campaigns.new campaign_params

    if campaign.save
      render json: campaign
    else
      render status: 400, json: { message: 'error. danger!!!' }
    end
  end

  def technology
    @name = params[:industry].capitalize
    @campaigns = Campaign.where(industry: @name).order(created_at: :desc)
  end

  def add_campaign_to_influencer
    @current_campaign = Campaign.find_by_id(params[:current_campaign_id])
    @current_campaign.influencers.push(current_influencer)
    
    redirect_to '/influencers/dashboard'
  end

  def destroy
    @current_campaign = Campaign.find_by_id(params[:current_campaign_id])
    @current_campaign.destroy

    redirect_to '/brands/dashboard'
  end


  private

  def campaign_params
    params.permit(:industry, :hashtag, :age_group, :demographic, :location)
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController

  def dashboard 
    @your_campaigns = current_influencer.campaigns.all.order(created_at: :desc)
  end

  def create
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

 def sign_up_params
   params.require(:influencer).permit(:username, :industry, :age, :location, :occupation, :email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:influencer).permit(:username, :industry, :age, :location, :occupation, :email, :password, :password_confirmation, :current_password)
 end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    render 'home'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/campaigns_apis_helper.rb
module CampaignsApisHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def resource_name
    :brand
  end

  def resource
    @resource ||= Brand.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:brand]
  end

  def influencer_resource_name
    :influencer
  end

  def influencer
    Influencer.new
  end
end

app/views/brands/dashboard.html.erb
<div id="brand-dashboard">

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header navigating">
                <%= image_tag("hash-money-logo-2.png") %>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Hello <%= current_brand.username %>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li>
                        <% if current_brand %>
                            <%= link_to 'Log Out', destroy_session_path(current_brand), method: 'delete' %>
                        <% else %>
                            <a href="" class="js-open-modal">Brand Login</a>
                        <% end %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="">
                            <a href="/brands/dashboard"><i class="fa fa-tasks fa-fw"></i> Create New Campaign</a>
                        </li>
                        <li class="">
                            <a href="/brands/campaigns/in_progress"><i class="fa fa-spinner fa-fw"></i> Campaigns in Progress</a>
                        </li>
                        <li class="">
                            <a href="/brands/campaigns/completed"><i class="fa fa-check fa-fw"></i> Completed Campaigns</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Create New Campaign</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-4 js-form-card">
                    <div class="wrapper">
                       <div class="hover panel">
                          <div class="front">
                            <div class="box1 panel-body">
                              <h1>Create<br>New Campaign</h1>
                                <i class="fa fa-plus fa-fw add-icon"></i>
                            </div>
                          </div>
                          <div class="back">
                            <div class="box2 panel-body">
                              <%= form_for(@campaign) do |f| %>
                              <%= devise_error_messages! %>

                            <div class="field">
                                <%= f.label :industry, 'Interests' %><br>
                                <%= f.collection_select(:industry, Industry.all, :name, :name, :class => "target-industry")%>
                              </div>
                              <br>
                              <div class="field">
                                <%= f.label :hashtag, 'Hashtags' %><br>
                                <%= f.text_field :hashtag, autocomplete: "off", :class => "target-hashtag" %>
                              </div>
                              <br>
                              <div class="field">
                                <%= f.label :age_group, 'Age Group' %><br>
                                <%= f.text_field :age_group, autocomplete: "off", :class => "target-age-group" %>
                              </div>
                              <br>
                              <div class="field">
                                <%= f.label :demographic, 'Demographic' %><br>
                                <%= f.text_field :demographic, autocomplete: "off", :class => "target-demographic" %>
                              </div>
                              <br>
                              <div class="field">
                                <%= f.label :location, 'Location' %><br>
                                <%= f.text_field :location, autocomplete: "off", :class => "target-location" %>
                              </div>

                              <div class="actions">
                                <br>
                                <%= f.submit "Create", :class => "create-btn js-add-campaign" %>
                              </div>
                            <% end %>

                            </div>
                          </div>
                      </div>
                </div>

                </div>
                <!-- /.col-lg-4 -->
                
                <% @brands_campaigns.each do |campaign| %>
                
                <div class="col-lg-4">
                    <div class="wrapper">
                       <div class="hover panel">
                          <div class="front">
                            <div class="box1 panel-body">
                              <h1>#<%= campaign.hashtag %></h1>
                              <i class="fa fa-eye fa-fw add-icon"></i>
                              <h4>View Campaign Details</h4>
                            </div>
                          </div>
                          <div class="back">
                            <div class="box2 panel-body">
                              <h3 class="campaign-details">Campaign Details</h3>
                              <ul>
                                <p>Industry: <%= campaign.industry %></p>
                                <p>Hashtag: #<%= campaign.hashtag %></p>
                                <p>Age Group: <%= campaign.age_group %></p>
                                <p>Demographic: <%= campaign.demographic %></p>
                                <p>Location: <%= campaign.location %></p>
                                <br><br>
                                <p><button><%= link_to('Delete', brands_campaigns_delete_path(campaign), method: :delete, data: { confirm: 'Are you sure?'}) %></button></p>
        
                              </ul>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>  

                <% end %>
                <!-- /.col-lg-4
            </div>
            <!-- /.row -->
            
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


</div>

app/views/brands/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/brands/tweets_complete.html.erb
<% @tweets.each do |levelsio| %>
  <li><%= levelsio %></li>
<% end %>

app/views/influencers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashmoney</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag "landing-page" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/site/home.html.erb
<div class="intro-header">
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-text navbar-header hello">
                <%= image_tag("hash-money-logo-2.png") %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <% if current_brand %>
                        <%= link_to 'Log Out', destroy_session_path(current_brand, current_influencer), method: 'delete' %>
                    <% elsif current_influencer %>
                        <%= link_to 'Log Out', destroy_session_path(current_influencer), method: 'delete' %>
                    <% else %>
                        <a href="" class="js-open-login-modal login">Log In</a>
                        <a href="" class="js-open-signup-modal signup">Sign Up</a>
                    <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->

            <div class="row">
                <div class="col-md-12">
                    <div class="intro-message">
                        <h1>Social Engagement. Automated.</h1>
                        <h3>We help local businesses reach their target audience by matching them with the top influencers in their industry. </h3>
                        <!-- <hr class="intro-divider"> -->
                        <ul class="list-inline intro-social-buttons">
                            <li>
                            
                                <a href="#" class="howItWorksButton">Learn More</a>
                            </li>
    
                            <li>
                                <a href="" class="createBrandButton js-open-signup-modal">Get Started</a>
                            </li>
                        </ul>
                    </div>
                  </div>
                </div>
</div>
      
      <div class="modal fade js-signup-modal">
        <div class="modal-dialog">
          <div class="modal-content center">
            <div class="modal-header">
              <h1>Which of these best describes you?</h1>
            </div>
            <div class="modal-body">
              <h1><a href="<%= new_brand_registration_path %>" class="createBrandButton js-open-modal">Brand</a></h1>
              <p>or</p>
              <h1><a href="<%= new_influencer_registration_path %>" class="createInfluencerButton js-open-modal-2">Influencer</a></h1>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

      <div class="modal fade js-login-modal">
        <div class="modal-dialog">
          <div class="modal-content center">
            <div class="modal-header">
              <h1>Welcome Back!</h1>
            </div>
            <div class="modal-body">
              <h1><a href="<%= new_brand_session_path %>" class="createBrandButton js-open-login-brand-modal">Brand</a></h1>
              <p>or</p>
              <h1><a href="<%= new_influencer_session_path %>" class="createInfluencerButton js-open-login-influencer-modal">Influencer</a></h1>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

      <div class="modal fade js-login-brand-modal">
          <div class="modal-dialog">
            <div class="modal-content center">

              <div class="modal-header">
                <!-- Close button -->
                
                </button>
              </div>

              <div class="modal-body">
                <h2>Log in as a Brand</h2>

                  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <br>
                    <div class="field">
                      <%= f.label :email %><br />
                      <%= f.email_field :email, autofocus: true %>
                    </div>
                    <br>
                    <div class="field">
                      <%= f.label :password %><br />
                      <%= f.password_field :password, autocomplete: "off" %>
                    </div>
                    <br>
                    <% if devise_mapping.rememberable? -%>
                      <div class="field">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me %>
                      </div>
                    <% end -%>
                    <br>

                    <div class="actions">
                      <%= f.submit "Log In" %>
                    </div>
                    <br>
                  <% end %>

                
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <div class="modal fade js-login-influencer-modal">
          <div class="modal-dialog">
            <div class="modal-content center">

              <div class="modal-header">
                <!-- Close button -->
                
                </button>
              </div>

              <div class="modal-body">
                <h2>Log In as an Influencer</h2>

                  <%= form_for(influencer, as: influencer_resource_name, url: session_path(influencer_resource_name)) do |f| %>
                    <br>
                    <div class="field">
                      <%= f.label :email %><br />
                      <%= f.email_field :email, autofocus: true %>
                    </div>
                    <br>
                    <div class="field">
                      <%= f.label :password %><br />
                      <%= f.password_field :password, autocomplete: "off" %>
                    </div>
                    <br>
                    <% if devise_mapping.rememberable? -%>
                      <div class="field">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me %>
                      </div>
                    <% end -%>
                    <br>
                    <div class="actions">
                      <%= f.submit "Log In" %>
                    </div>
                  <% end %>
                    <br>


              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


        <div class="modal fade js-modal">
          <div class="modal-dialog">
            <div class="modal-content center">

              <div class="modal-header">
                <!-- Close button -->
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span>&times;</span>
                </button>

                <h2>Get Started as a Brand</h2>
              </div>

              <div class="modal-body">
                <h2>Sign up</h2>

                    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                      <%= devise_error_messages! %>
                      <br>
                      <div class="field">
                        <%= f.label :email %><br />
                        <%= f.email_field :email, autofocus: true %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :username %><br />
                        <%= f.text_field :username, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :password %>
                        <% if @validatable %>
                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                        <% end %><br />
                        <%= f.password_field :password, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :password_confirmation %><br />
                        <%= f.password_field :password_confirmation, autocomplete: "off" %>
                      </div> 
                      <br>
                      <div class="actions">
                        <%= f.submit "Sign up" %>
                      </div>
                    <% end %>
                    <br>
                    <%= link_to "Log In", new_brand_session_path %>

              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <div class="modal fade js-modal-2">
          <div class="modal-dialog">
            <div class="modal-content center">

              <div class="modal-header">
                <!-- Close button -->
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span>&times;</span>
                </button>

                <h2>Get Started as an Influencer</h2>
              </div>

              <div class="modal-body">
                <h2>Sign up</h2>

                    <%= form_for(influencer, as: influencer_resource_name, url: registration_path(influencer_resource_name)) do |f| %>
                      <%= devise_error_messages! %>
                      <br>
                      <div class="field">
                        <%= f.label :email %><br />
                        <%= f.email_field :email, autofocus: true %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :username %><br />
                        <%= f.text_field :username, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :password %>
                        <% if @validatable %>
                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                        <% end %><br />
                        <%= f.password_field :password, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :password_confirmation %><br />
                        <%= f.password_field :password_confirmation, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :age %><br />
                        <%= f.text_field :age, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :occupation %><br />
                        <%= f.text_field :occupation, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :location %><br />
                        <%= f.text_field :location, autocomplete: "off" %>
                      </div>
                      <br>
                      <div class="field">
                        <%= f.label :industry, 'Interests' %><br>
                        <%= f.collection_select(:industry, Industry.all, :name, :name, :class => "target-industry")%>
                      </div>
                      <br>
                      <div class="actions">
                        <%= f.submit "Sign up" %>
                      </div>
                    <% end %>
                    <br>
                    <%= link_to "Log In", new_influencer_session_path %><br>
                    <%= link_to "Forgot your password?", new_influencer_password_path %>
                    
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>




        